
import React, { useState } from 'react'
import "./App.css"
import Menu from './Menu/Menu'

const App = () => {
  const [menuActive, setMenuActive] = useState(false);
  const items = [
    {value:"Главная", href:"/main", icon: "anchor"},
    {value:"Услуги", href:"/service", icon: "api"},
    {value:"Магазин", href:"/shop", icon: "android"},
    {value:"О нас", href:"/about", icon: "android"}             
  ]
  return (
    <div className="app">
      <nav>
        <div className="burger-btn" onClick={() => setMenuActive(!menuActive)}>
          <span />
        </div>
      </nav>
      <main>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nemo adipisci, laboriosam voluptatibus corrupti praesentium provident dicta veniam consequatur saepe aspernatur, minus eveniet in voluptate blanditiis delectus, explicabo laudantium eius animi fugiat voluptatem? Sint veritatis, illum quis fuga pariatur error consectetur suscipit laudantium magnam porro id nam aperiam molestias dicta provident facere saepe maxime repellendus inventore dolorum hic velit voluptate nobis tempore! Dolorum, possimus! At asperiores veniam, earum rem, blanditiis atque ut saepe explicabo cum tenetur incidunt perspiciatis laborum expedita maiores ullam nesciunt ipsum repudiandae magni consectetur enim velit natus nulla commodi? Magnam saepe consequuntur eaque hic reiciendis molestias deleniti quia. Perferendis atque eligendi fugiat voluptate quidem dicta ut, itaque quibusdam placeat tempora dolore optio animi nihil iste hic quo tempore quas earum blanditiis, unde aliquam beatae consectetur fuga. Ab natus rem consectetur corrupti quis ipsam unde debitis consequuntur, harum voluptates quia velit voluptate commodi consequatur cupiditate veniam quae mollitia tempora nulla necessitatibus porro veritatis magni. Voluptas sed quia aspernatur facilis, tempore ab id commodi voluptatem dolor natus cumque eligendi ullam accusamus nemo sunt itaque. Ipsam fugiat eum tempora. Saepe id, recusandae perspiciatis eaque veniam, doloremque accusantium accusamus maiores ex voluptate quia itaque odit deleniti vero, enim impedit nesciunt eos consequatur?</p>
        <p>Fuga iusto perspiciatis eveniet ex quas expedita sit iste omnis! Amet magni fugiat obcaecati beatae illo unde nostrum cumque, facilis facere possimus labore magnam fugit, deserunt dignissimos. Sint veniam, iste voluptatem delectus voluptatum, dignissimos mollitia aliquam quas tempora ea illum corporis rem, iure quibusdam dicta ex consectetur. Quo iste ipsum illum velit repellat suscipit delectus veritatis recusandae dicta laborum amet rem fuga quidem consequatur, aspernatur asperiores quaerat sapiente eos ratione perferendis modi totam dignissimos. Totam quidem cupiditate distinctio unde reprehenderit ab doloribus eum fugiat ullam? Numquam, voluptates animi similique fugit minima voluptate alias? Voluptatibus nobis aut quibusdam ratione eligendi ipsam voluptas eveniet sed eius assumenda alias, rerum odio et molestias enim quo unde esse facere nostrum possimus ad necessitatibus dignissimos. Quae sunt tempore officiis, soluta laborum commodi voluptate amet reiciendis delectus distinctio consequuntur adipisci deserunt doloremque praesentium quam quisquam autem porro libero! Aliquid voluptas ex, inventore corrupti cum natus ratione eos laboriosam laudantium amet magnam, in reprehenderit non similique? Quos quisquam iure sit doloremque consectetur. Ipsa accusantium blanditiis debitis ratione optio facere, totam mollitia tempora, repudiandae corrupti excepturi, nobis beatae fugiat? Quo, tenetur itaque consectetur ex dolore corrupti velit repudiandae, optio molestiae facere autem dignissimos porro ab perspiciatis earum ratione?</p>
        <p>Dicta nostrum adipisci sequi rerum tempore, eos, voluptate odit quisquam vero vel modi cupiditate laborum nobis blanditiis rem commodi totam ipsam, mollitia neque! Fugit fugiat quaerat nulla corporis excepturi cupiditate consectetur fuga voluptate velit laudantium quod deleniti optio, aspernatur tenetur assumenda dolorem unde possimus. At architecto rerum earum quam modi quia recusandae vitae quisquam laudantium molestiae nisi natus ullam aperiam corrupti quis optio veritatis, magnam autem culpa! Similique, beatae unde! Dolor asperiores dolorum rerum cupiditate vitae? Ex odit sint tenetur maxime nulla, quidem similique numquam esse cum. Corrupti natus voluptatibus reprehenderit harum nostrum aperiam quia eaque culpa quis quasi ducimus ea vel dicta tempora obcaecati ab fugit ut, nobis est! Nobis illo quidem, qui quia nemo temporibus ut similique quod error ea quaerat culpa ad velit, ipsum excepturi non officiis, a tenetur! Repellendus quod veritatis, quis enim voluptatem porro minima earum nesciunt exercitationem est impedit voluptates aut debitis sint a eligendi sed laudantium labore sunt dolorem nihil itaque pariatur esse natus. Esse reiciendis beatae magni in repellendus ipsum commodi accusantium veniam veritatis. Cupiditate amet non officiis possimus, est tenetur fugiat qui dolore sunt inventore accusantium illum nulla voluptates quaerat quod itaque sint consequatur nostrum numquam. Voluptate aspernatur nisi corporis accusantium.</p>
        <p>Harum magnam perferendis tempore ut, et possimus ex placeat perspiciatis magni fugiat quia iste ipsa optio explicabo. Molestiae, qui corporis ab enim voluptatibus fuga esse voluptatum officiis sint, obcaecati eos, facilis illo! Ad dignissimos autem eum porro optio velit placeat, architecto, debitis et rerum odio at. Doloribus eligendi velit, recusandae sed placeat aut, harum quia necessitatibus ipsa quae suscipit! Recusandae eligendi assumenda quia consequatur sit laudantium magnam dolorem odio sed veniam ullam commodi qui, distinctio itaque earum soluta! Iste, iusto optio. Vel saepe odit eligendi ab voluptatem illo laborum neque velit, adipisci obcaecati minus minima molestias earum rem explicabo voluptatibus aut vitae doloribus porro consequatur? Deleniti ipsa veritatis inventore libero maxime ad doloremque obcaecati hic harum ex, fuga quo laudantium dicta fugiat temporibus tempora necessitatibus, quibusdam voluptatum, magni sit aspernatur magnam. Mollitia hic deserunt architecto laborum id, dignissimos quis tempore voluptate maiores possimus nobis reiciendis consectetur quo, natus minus quasi odio voluptas magnam. A suscipit, itaque nam iusto assumenda hic neque laboriosam vel temporibus voluptas pariatur adipisci. Distinctio consectetur optio laborum assumenda dolores perspiciatis totam architecto est, iusto neque velit quae quasi quis alias eum. Eligendi, molestiae at. Eius, hic incidunt minus quibusdam aliquam nihil corporis. Totam libero id dolore?</p>
        <p>Ullam inventore corporis saepe illo totam, tenetur qui, sapiente magnam fugit sit eaque sed pariatur ipsam delectus, culpa minus officia hic commodi porro? Velit fugiat dolore, itaque nam at voluptatem voluptatibus aliquam omnis ex eaque eius! Ea facere maiores a repellat nesciunt eius blanditiis dolorum debitis perspiciatis sint, consectetur pariatur est facilis accusamus explicabo sequi quidem ipsam id doloribus deserunt dicta dolores. Veritatis, aspernatur sapiente ut neque aliquam ea beatae corrupti ad doloremque repellendus molestiae rem obcaecati animi explicabo consequatur nulla autem quo alias nemo esse quod ex praesentium impedit! Ea asperiores, id, ipsa delectus perspiciatis ut est eaque ullam, cumque officia amet architecto molestias placeat aliquam? Quam saepe modi quos perferendis aperiam, tempora libero, optio nisi, sint nemo itaque sapiente. Repellendus consequatur sequi ipsa eaque placeat aliquam numquam iusto sit quidem, doloribus illum est atque animi quibusdam ullam maxime saepe! Unde facilis, dolores dolorem rerum quas quos laborum earum soluta rem, molestiae nobis recusandae libero ratione odio? Molestiae deleniti molestias fugiat cupiditate, eligendi, aperiam recusandae facilis error aut labore modi magni mollitia voluptatum obcaecati quia quas, voluptate nisi minus temporibus fugit accusamus ad quod. Sit esse nisi, cum cumque minima earum officia sapiente animi amet. Ea unde sunt officiis?</p>
        <p>Totam itaque, porro illo culpa, a consectetur impedit, doloribus quo quas ex quaerat reprehenderit. Vitae, quas. Sunt ipsa non harum cum animi! Eligendi quos possimus iusto in nisi voluptates, corporis odio hic ipsam sequi dicta explicabo impedit laborum aliquid quisquam nihil voluptas nemo cum voluptatum qui ipsum vero? Deleniti dolorem reiciendis laudantium aspernatur dignissimos quibusdam placeat consequatur earum itaque consectetur necessitatibus adipisci unde, nihil quas? Assumenda ipsum ipsa saepe nisi molestiae ipsam dolorem sunt similique sapiente ratione tenetur ea quaerat, eius velit, sed corporis soluta. Quis iusto voluptas atque vero ut eveniet, suscipit in recusandae harum commodi? Doloribus, sint, voluptatibus fuga dignissimos incidunt blanditiis eum quam ipsam dolore error sunt nobis! Porro optio cupiditate fuga labore cum debitis, numquam nam facere omnis atque earum. Qui illum vitae quaerat totam ut sed beatae maiores, modi atque dolorum enim accusamus placeat nesciunt similique incidunt perspiciatis vel. Praesentium quod rerum reiciendis! Cum fugiat odit debitis omnis officiis quia optio minus pariatur consectetur obcaecati. Expedita, culpa? Beatae unde dolorum temporibus accusamus quod. Fugit nobis accusamus porro vitae deleniti ipsa laboriosam itaque explicabo quaerat accusantium quisquam tempora in, commodi quod. Saepe provident velit quo optio perferendis minus, quas, dolor delectus dignissimos nihil nesciunt laboriosam cupiditate!</p>
        <p>Saepe ducimus veniam veritatis? Obcaecati perferendis sunt, eos explicabo fugit fuga nihil maiores. Reprehenderit numquam facilis consequuntur corrupti maiores, quam aliquid? Animi perferendis voluptatibus, a hic repellat ducimus adipisci laborum! Corporis doloribus dolorum accusantium, sunt illo dolore illum odit obcaecati repellendus hic, odio voluptates sequi cum earum vitae voluptatum sed consectetur eius quos? Aperiam doloremque, fugiat, unde delectus autem dolorum, laboriosam sapiente temporibus molestias consequatur reprehenderit maxime. Officia vero accusamus corporis repellat temporibus sequi vitae dicta autem ipsam dolore iure sint necessitatibus ullam, illo ratione ducimus cumque, facere iste corrupti. Nisi asperiores cupiditate illo dolores est distinctio, sequi aperiam assumenda consequatur consequuntur dicta harum quia voluptate quidem tempora voluptas? Maiores numquam quas obcaecati mollitia blanditiis rerum incidunt quo quis, praesentium quam reiciendis aliquid dolor facilis eligendi, autem sapiente corrupti hic ipsa. Consequuntur maiores architecto vero commodi eveniet molestiae distinctio saepe quis facilis ratione nihil est repudiandae possimus impedit voluptatum sint, repellat esse quae ipsum in quia assumenda alias officiis. Amet, pariatur. Ratione pariatur ducimus amet ad a vel impedit. Labore asperiores deserunt illum quia porro culpa ab debitis, fugiat rerum aperiam praesentium iste vero error eligendi alias ullam! Perferendis in et non animi nam commodi reiciendis unde deserunt a doloremque.</p>
      </main>
      <Menu active={menuActive} setActive={setMenuActive} header={"Бургер Меню"} items={items} />
    </div>
  )
}

export default App
